### ISSUE TITLE
Error creating release with unaltered charts

### ISSUE THREAD

**Issue by Juanezm** [helm/chart-releaser-action#30]
I'm having an error every time I create a new release, with a chart that hasn't been modified tries to be released, and of course already exists.

The chart folder of my repo contains two charts, and I'm only want to modify and release one of them, but the second one is packaged and failing when releasing.

```
Packaging chart 'charts/geoserver'...
Successfully packaged chart and saved it to: .cr-release-packages/geoserver-0.1.1.tgz
Packaging chart 'charts/terria'...
Successfully packaged chart and saved it to: .cr-release-packages/terria-0.2.5.tgz
Releasing charts...
Error: error creating GitHub release: POST https://api.github.com/repos/Juanezm/csvs-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
Usage:
  cr upload [flags]

Flags:
  -b, --git-base-url string     GitHub Base URL (only needed for private GitHub) (default "https://api.github.com/")
  -r, --git-repo string         GitHub repository
  -u, --git-upload-url string   GitHub Upload URL (only needed for private GitHub) (default "https://uploads.github.com/")
  -h, --help                    help for upload
  -o, --owner string            GitHub username or organization
  -p, --package-path string     Path to directory with chart packages (default ".cr-release-packages")
  -t, --token string            GitHub Auth Token

Global Flags:
      --config string   Config file (default is $HOME/.cr.yaml)
```

Is there any way to prevent this from happening without incrementing the unchanged chart's version?

Thanks

**Comment by tony-kerz** [comment]
i just encountered [this](https://github.com/the-watchmen/helm-charts/runs/882627391?check_suite_focus=true) as well:

```
helm-charts
Looking up latest tag...
Discovering changed charts since 'job-1.1.0'...
Installing chart-releaser...
Packaging chart 'charts/ingress'...
Successfully packaged chart and saved it to: .cr-release-packages/config-map-1.0.0.tgz
Packaging chart 'charts/secret'...
Successfully packaged chart and saved it to: .cr-release-packages/config-map-1.0.0.tgz
Releasing charts...
Error: error creating GitHub release: POST https://api.github.com/repos/the-watchmen/helm-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
Usage:
  cr upload [flags]

Flags:
  -b, --git-base-url string     GitHub Base URL (only needed for private GitHub) (default "https://api.github.com/")
  -r, --git-repo string         GitHub repository
  -u, --git-upload-url string   GitHub Upload URL (only needed for private GitHub) (default "https://uploads.github.com/")
  -h, --help                    help for upload
  -o, --owner string            GitHub username or organization
  -p, --package-path string     Path to directory with chart packages (default ".cr-release-packages")
  -t, --token string            GitHub Auth Token

Global Flags:
      --config string   Config file (default is $HOME/.cr.yaml)
```

turns out i accidentally had the same chart name in different chart folders, 
so that must have triggered the duplicate situation.

i think it would be helpful if this error was actually populated with the correct values to assist in trouble-shooting:

```
Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```

**Comment by lippertmarkus** [comment]
This is now solved with v1.0.0

**Comment by Juanezm** [comment]
> 
> 
> This is now solved with v1.0.0

It doesn't solve the issue to me

`
Run helm/chart-releaser-action@v1.0.0
csvs-charts
Looking up latest tag...
Discovering changed charts since 'geoserver-0.1.1'...
Installing chart-releaser...
Packaging chart 'charts/geoserver'...
Successfully packaged chart and saved it to: .cr-release-packages/geoserver-0.1.1.tgz
Packaging chart 'charts/terria'...
Successfully packaged chart and saved it to: .cr-release-packages/terria-0.3.1.tgz
Releasing charts...
Error: error creating GitHub release: POST https://api.github.com/repos/Juanezm/csvs-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
`

**Comment by lippertmarkus** [comment]
@Juanezm you of course need to increment the version of the Chart as charts should be immutable. What's solved with v1.0.0 is that chart-releaser doesn't try to publish unaltered charts.

**Comment by Juanezm** [comment]
> 
> 
> @Juanezm you of course need to increment the version of the Chart as charts should be immutable. What's solved with v1.0.0 is that chart-releaser doesn't try to publish unaltered charts.

Sure, that is what I'm doing in the example above, I have 2 charts, terria and geoserver. I only make changes and increase the version to terria, but it fails when trying to publishing also geoserver, and of course a previous version exists.

**Comment by lippertmarkus** [comment]
hm okay strange, I did basically the same in my repo (https://github.com/lippertmarkus/helm-charts) and it worked without a problem. It just detected the one chart that changed and released this one.

**Comment by Juanezm** [comment]
I finally found the issue and it was caused by another step in the workflow. I can confirm that this action works perfectly 👍
